package healer

import (
	"strings"
	"testing"
)

// TestDeterministicPythonVersionBump: a pip "requires a different Python
// >= 3.13" failure against a python:3.12-slim Dockerfile is repaired by
// bumping the base image — deterministically, with no LLM. This is the
// engine behind the hackathon's broken-demo fixture.
func TestDeterministicPythonVersionBump(t *testing.T) {
	dockerfile := `# Generated by Yoink.
FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir .
COPY . .
CMD ["python", "app.py"]
`
	// Realistic pip error shape.
	errTail := `#9 1.234 ERROR: Package 'demo' requires a different Python: 3.12.0 not in '<requires-python>' (>=3.13).`
	fixed, summary, ok := DeterministicFix(errTail, dockerfile, "")
	if !ok {
		t.Fatal("expected a deterministic fix, got none")
	}
	if !strings.Contains(fixed, "FROM python:3.13-slim") {
		t.Errorf("fix should bump to python:3.13-slim, got:\n%s", fixed)
	}
	if !strings.Contains(summary, "3.13") {
		t.Errorf("summary should mention 3.13, got %q", summary)
	}
	// The fix must not duplicate the FROM line or drop the rest.
	if strings.Count(fixed, "FROM python:") != 1 {
		t.Errorf("fix should keep exactly one FROM line, got %d", strings.Count(fixed, "FROM python:"))
	}
	if !strings.Contains(fixed, `CMD ["python", "app.py"]`) {
		t.Error("fix should preserve the CMD line")
	}
}

// TestDeterministicNoFixWhenVersionSatisfies: when the base already meets
// the requirement, the fixer must NOT fire (no needless churn).
func TestDeterministicNoFixWhenVersionSatisfies(t *testing.T) {
	dockerfile := "FROM python:3.13-slim\nWORKDIR /app\n"
	errTail := "ERROR: Package 'demo' requires a different Python: 3.12.0 not in '<requires-python>' (>=3.13)."
	_, _, ok := DeterministicFix(errTail, dockerfile, "")
	if ok {
		t.Fatal("should not fix when the base already satisfies the requirement")
	}
}

// TestDeterministicNoFixWhenNoPythonFrom: if the Dockerfile has no python
// base line, the fixer declines rather than guessing.
func TestDeterministicNoFixWhenNoPythonFrom(t *testing.T) {
	dockerfile := "FROM node:20-alpine\nWORKDIR /app\n"
	errTail := "ERROR: requires a different Python: ... >= 3.13."
	_, _, ok := DeterministicFix(errTail, dockerfile, "")
	if ok {
		t.Fatal("should not fix a non-python Dockerfile")
	}
}
