package cmd

import (
	"reflect"
	"testing"

	"yoink/internal/detector"
	"yoink/internal/llm"
)

// Regression: LLM-corrected services must preserve InstallCmd/StartCmd so the
// Dockerfile generator doesn't emit `RUN ` (empty) + the no-start-cmd fallback.
// Previously applyServiceCorrections built a bare Service from the LLM stub,
// which made the generated Dockerfile a no-op image.
func TestMergeServiceCorrectionsPreservesCommands(t *testing.T) {
	original := []detector.Service{{
		ID:             "service-1",
		Type:           "backend",
		Directory:      "",
		Language:       "python",
		Framework:      "django",
		PackageManager: "pip",
		InstallCmd:     []string{"pip", "install", "--no-cache-dir", "-r", "requirements.txt"},
		StartCmd:       []string{"python", "manage.py", "runserver", "0.0.0.0:8000"},
		Port:           8000,
		Confidence:     "high",
	}}
	corrections := []llm.CorrectedService{{
		Directory:  "",
		Framework:  "django",
		Type:       "backend",
		Confidence: 0.95,
	}}
	merged, changed := mergeServiceCorrections(original, corrections)
	if changed {
		t.Errorf("LLM agreed with detection; expected changed=false")
	}
	if len(merged) != 1 {
		t.Fatalf("expected 1 service, got %d", len(merged))
	}
	if !reflect.DeepEqual(merged[0].InstallCmd, original[0].InstallCmd) {
		t.Errorf("install cmd lost: got %v", merged[0].InstallCmd)
	}
	if !reflect.DeepEqual(merged[0].StartCmd, original[0].StartCmd) {
		t.Errorf("start cmd lost: got %v", merged[0].StartCmd)
	}
	if merged[0].Port != 8000 {
		t.Errorf("port lost: got %d", merged[0].Port)
	}
}

// Regression: the LLM frequently emits "." for the repo root while the
// detector uses "". Both must resolve to the same key when merging.
func TestMergeServiceCorrectionsNormalisesRootDir(t *testing.T) {
	original := []detector.Service{{
		ID: "service-1", Directory: "", Framework: "django", Type: "backend",
		InstallCmd: []string{"pip", "install", "-r", "requirements.txt"},
		StartCmd:   []string{"python", "manage.py", "runserver", "0.0.0.0:8000"},
		Port:       8000,
	}}
	corrections := []llm.CorrectedService{{
		Directory: ".", Framework: "django", Type: "backend", Confidence: 0.95,
	}}
	merged, _ := mergeServiceCorrections(original, corrections)
	if len(merged) != 1 {
		t.Fatalf("expected 1 service, got %d", len(merged))
	}
	if len(merged[0].InstallCmd) == 0 || len(merged[0].StartCmd) == 0 {
		t.Errorf("commands were dropped because '.' wasn't normalised to '': %+v", merged[0])
	}
}

func TestMergeServiceCorrectionsAppliesFrameworkChange(t *testing.T) {
	original := []detector.Service{{
		ID: "service-1", Directory: "", Framework: "node", Type: "backend",
		InstallCmd: []string{"npm", "ci"}, StartCmd: []string{"npm", "start"},
	}}
	corrections := []llm.CorrectedService{{
		Directory: "", Framework: "express", Type: "backend", Confidence: 0.9,
	}}
	merged, changed := mergeServiceCorrections(original, corrections)
	if !changed {
		t.Errorf("framework changed node→express; expected changed=true")
	}
	if merged[0].Framework != "express" {
		t.Errorf("framework not updated: got %s", merged[0].Framework)
	}
	// Existing commands are preserved; the language is preserved (node/express both javascript).
	if len(merged[0].InstallCmd) == 0 {
		t.Errorf("install cmd was nuked by a same-language framework change")
	}
}

func TestExtractPortMapReadsHostPort(t *testing.T) {
	compose := `# Generated by Yoink. Run from repo root:
#   docker compose -f yoink-outputs/docker-compose.yml up

services:
  service-1:
    build:
      context: ..
      dockerfile: yoink-outputs/Dockerfile.service-1
    container_name: yoink-acme-service-1
    ports:
      - "3000:3000"
    env_file:
      - env-vars/service-1/.env
    networks:
      - acme-net

  service-2:
    build:
      context: ..
      dockerfile: yoink-outputs/Dockerfile.service-2
    container_name: yoink-acme-service-2
    ports:
      - "8001:8000"
    env_file:
      - env-vars/service-2/.env
    networks:
      - acme-net

networks:
  acme-net:
    driver: bridge
`
	svcs := []detector.Service{{ID: "service-1"}, {ID: "service-2"}}
	got := extractPortMap(compose, svcs)
	if got["service-1"] != 3000 {
		t.Errorf("expected service-1 -> 3000, got %d", got["service-1"])
	}
	if got["service-2"] != 8001 {
		t.Errorf("expected service-2 -> 8001 (remap), got %d", got["service-2"])
	}
}

func TestExtractPortMapIgnoresDependsOnDashLines(t *testing.T) {
	compose := `services:
  service-1:
    depends_on:
      - postgres
    ports:
      - "9000:9000"
`
	got := extractPortMap(compose, []detector.Service{{ID: "service-1"}})
	if got["service-1"] != 9000 {
		t.Errorf("expected 9000, got %d", got["service-1"])
	}
}
