package cmd

import (
	"fmt"
	"strings"

	"yoink/internal/detector"
)

func quickStart(repo string, services []detector.Service, outDir string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Quick Start — %s\n\n", repo)
	fmt.Fprintf(&b, "Generated by Yoink %s\n\n", Version)

	b.WriteString("## Detected services\n\n")
	for _, s := range services {
		dir := s.Directory
		if dir == "" {
			dir = "."
		}
		fmt.Fprintf(&b, "- **%s** — %s (%s) in `%s/` · port %d\n", s.ID, s.Framework, s.Type, dir, s.Port)
	}

	b.WriteString("\n## Run with Yoink (recommended)\n\n```sh\n")
	fmt.Fprintf(&b, "yoink up %s         # build, start, wait for healthchecks\n", repo)
	fmt.Fprintf(&b, "yoink dash %s       # multi-pane dashboard\n", repo)
	fmt.Fprintf(&b, "yoink down %s       # stop\n", repo)
	b.WriteString("```\n\n")

	b.WriteString("## Run with raw docker compose\n\n```sh\n")
	b.WriteString("# 1. Edit per-service env files (already seeded from .env.example)\n")
	for _, s := range services {
		fmt.Fprintf(&b, "$EDITOR %s/env-vars/%s/.env\n", outDir, s.ID)
	}
	fmt.Fprintf(&b, "\n# 2. Build and start\ndocker compose -f %s/docker-compose.yml up --build\n", outDir)
	fmt.Fprintf(&b, "\n# 3. View logs\ndocker compose -f %s/docker-compose.yml logs -f\n", outDir)
	fmt.Fprintf(&b, "\n# 4. Stop\ndocker compose -f %s/docker-compose.yml down\n```\n\n", outDir)

	b.WriteString("## Endpoints\n\n")
	for _, s := range services {
		fmt.Fprintf(&b, "- %s → http://localhost:%d\n", s.ID, s.Port)
	}

	b.WriteString("\n## Notes\n\n")
	b.WriteString("- `.env.example` is the template (safe to commit). `.env` is the file\n")
	b.WriteString("  compose actually reads. The `.env` here was seeded from the template;\n")
	b.WriteString("  fill in real values before running anything that touches production.\n")
	b.WriteString("- `yoink up` re-renders `.env` from `.env.example` + per-key overrides\n")
	b.WriteString("  in `~/.yoink/state/" + repo + "/env-overrides.json`. Edit through the\n")
	b.WriteString("  dashboard (`yoink dash " + repo + "` → e) to persist your changes.\n")
	return b.String()
}
