package generator

import (
	"fmt"
	"sort"
	"strings"

	"yoink/internal/detector"
	"yoink/internal/healthcheck"
	"yoink/internal/infra"
	"yoink/internal/portprobe"
)

// Options controls how Build assembles compose / Dockerfile output.
type Options struct {
	// Repo is the upstream repository name; used for the network and
	// container-name prefix.
	Repo string
	// OutputSubdir is the directory (relative to the repo root) where
	// generated files will live, e.g. "yoink-outputs".
	OutputSubdir string
	// Infra is an optional list of inferred backing services to add to the
	// compose stack (postgres, redis, etc.). Each entry produces one extra
	// compose service.
	Infra []infra.Service
	// Links maps an application service ID to the infra services it depends
	// on. Each entry produces a depends_on block with a service_healthy
	// condition (when the infra has a healthcheck).
	Links map[string][]infra.AppLink
	// PortFn picks a free host port given a preferred container port. When
	// nil a port-probing allocator is used. Tests can supply a deterministic
	// stub.
	PortFn func(preferred int) int
}

func (o *Options) outputSubdir() string {
	if o.OutputSubdir == "" {
		return "yoink-outputs"
	}
	return o.OutputSubdir
}

func (o *Options) portFn() func(int) int {
	if o.PortFn != nil {
		return o.PortFn
	}
	alloc := portprobe.New()
	return alloc.Allocate
}

// renderCompose generates docker-compose.yml. The compose file lives at
// <repo>/<outputSubdir>/docker-compose.yml — every path is relative to that
// location so the user can run `docker compose -f
// <outputSubdir>/docker-compose.yml up` from the repo root with no further
// edits.
func renderCompose(services []detector.Service, opts Options) string {
	subdir := opts.outputSubdir()
	project := safeProjectName(opts.Repo)
	net := project + "-net"

	var b strings.Builder
	b.WriteString("# Generated by Yoink. Run from repo root:\n")
	fmt.Fprintf(&b, "#   docker compose -f %s/docker-compose.yml up\n\n", subdir)
	b.WriteString("services:\n")

	pickPort := opts.portFn()

	// Application services first.
	for _, svc := range services {
		writeAppService(&b, svc, project, net, subdir, pickPort, opts.Links[svc.ID], opts.Infra)
	}

	// Backing services (databases, caches, queues) come last so a casual
	// reader can scan the app services without scrolling.
	// Skip external provider infra — it's not provisioned locally.
	for _, infraSvc := range opts.Infra {
		if infraSvc.Mode == "external" {
			continue // external provider (Neon, Upstash, etc.) — no local container
		}
		writeInfraService(&b, infraSvc, project, net, pickPort)
	}

	b.WriteString("networks:\n")
	fmt.Fprintf(&b, "  %s:\n", net)
	b.WriteString("    driver: bridge\n")

	if vols := collectVolumes(opts.Infra); len(vols) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, v := range vols {
			fmt.Fprintf(&b, "  %s:\n", v)
		}
	}
	return b.String()
}

func writeAppService(b *strings.Builder, svc detector.Service, project, net, subdir string, pickPort func(int) int, links []infra.AppLink, infraSvcs []infra.Service) {
	name := safeServiceName(svc.ID)
	port := svc.Port
	if port == 0 {
		port = 3000
	}
	hostPort := pickPort(port)

	fmt.Fprintf(b, "  %s:\n", name)
	b.WriteString("    build:\n")
	b.WriteString("      context: ..\n")
	fmt.Fprintf(b, "      dockerfile: %s/Dockerfile.%s\n", subdir, svc.ID)
	fmt.Fprintf(b, "    container_name: %s-%s\n", project, name)
	b.WriteString("    ports:\n")
	fmt.Fprintf(b, "      - \"%d:%d\"\n", hostPort, port)
	b.WriteString("    env_file:\n")
	fmt.Fprintf(b, "      - env-vars/%s/.env\n", svc.ID)
	b.WriteString("    restart: on-failure:5\n")

	// Build a set of external (skipped) service names — we must NOT
	// add depends_on for them since they won't be in the compose file.
	external := map[string]bool{}
	for _, isvc := range infraSvcs {
		if isvc.Mode == "external" {
			external[isvc.Name] = true
		}
	}

	// Only add depends_on for non-external infra services.
	var validLinks []infra.AppLink
	for _, link := range links {
		if !external[link.ServiceName] {
			validLinks = append(validLinks, link)
		}
	}

	if len(validLinks) > 0 {
		b.WriteString("    depends_on:\n")
		for _, link := range validLinks {
			fmt.Fprintf(b, "      %s:\n", link.ServiceName)
			b.WriteString("        condition: service_healthy\n")
		}
	}

	writeHealthcheck(b, healthcheckSpec(healthcheck.ForApp(svc.Framework, port)))

	b.WriteString("    networks:\n")
	fmt.Fprintf(b, "      - %s\n\n", net)
}

func writeInfraService(b *strings.Builder, svc infra.Service, project, net string, pickPort func(int) int) {
	fmt.Fprintf(b, "  %s:\n", svc.Name)
	fmt.Fprintf(b, "    image: %s\n", svc.Image)
	fmt.Fprintf(b, "    container_name: %s-%s\n", project, svc.Name)
	b.WriteString("    restart: unless-stopped\n")

	if len(svc.Env) > 0 {
		b.WriteString("    environment:\n")
		keys := make([]string, 0, len(svc.Env))
		for k := range svc.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(b, "      %s: %q\n", k, svc.Env[k])
		}
	}

	if svc.Port != 0 || len(svc.ExtraPorts) > 0 {
		b.WriteString("    ports:\n")
		if svc.Port != 0 {
			fmt.Fprintf(b, "      - \"%d:%d\"\n", pickPort(svc.Port), svc.Port)
		}
		for _, p := range svc.ExtraPorts {
			fmt.Fprintf(b, "      - \"%d:%d\"\n", pickPort(p), p)
		}
	}

	if svc.VolumeName != "" && svc.VolumePath != "" {
		b.WriteString("    volumes:\n")
		fmt.Fprintf(b, "      - %s:%s\n", svc.VolumeName, svc.VolumePath)
	}

	writeHealthcheck(b, infraHealthcheck(svc.Healthcheck))

	b.WriteString("    networks:\n")
	fmt.Fprintf(b, "      - %s\n\n", net)
}

// healthcheckSpec normalises a healthcheck.Spec onto the same internal shape
// we use for infra healthchecks, so writeHealthcheck has a single rendering
// path.
type internalCheck struct {
	Test        []string
	Interval    string
	Timeout     string
	Retries     int
	StartPeriod string
}

func healthcheckSpec(s healthcheck.Spec) internalCheck {
	return internalCheck{Test: s.Test, Interval: s.Interval, Timeout: s.Timeout, Retries: s.Retries, StartPeriod: s.StartPeriod}
}

func infraHealthcheck(h infra.Healthcheck) internalCheck {
	return internalCheck{Test: h.Test, Interval: h.Interval, Timeout: h.Timeout, Retries: h.Retries}
}

func writeHealthcheck(b *strings.Builder, c internalCheck) {
	if len(c.Test) == 0 {
		return
	}
	b.WriteString("    healthcheck:\n")
	b.WriteString("      test: [")
	parts := make([]string, len(c.Test))
	for i, t := range c.Test {
		parts[i] = fmt.Sprintf("%q", t)
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString("]\n")
	if c.Interval != "" {
		fmt.Fprintf(b, "      interval: %s\n", c.Interval)
	}
	if c.Timeout != "" {
		fmt.Fprintf(b, "      timeout: %s\n", c.Timeout)
	}
	if c.Retries > 0 {
		fmt.Fprintf(b, "      retries: %d\n", c.Retries)
	}
	if c.StartPeriod != "" {
		fmt.Fprintf(b, "      start_period: %s\n", c.StartPeriod)
	}
}

func collectVolumes(svcs []infra.Service) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range svcs {
		if s.Mode == "external" {
			continue
		}
		if s.VolumeName == "" || seen[s.VolumeName] {
			continue
		}
		seen[s.VolumeName] = true
		out = append(out, s.VolumeName)
	}
	sort.Strings(out)
	return out
}

func safeServiceName(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "_", "-")
	return s
}

func safeProjectName(name string) string {
	name = strings.ToLower(name)
	var out strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
		case r == '-', r == '_':
			out.WriteRune(r)
		default:
			out.WriteRune('-')
		}
	}
	if out.Len() == 0 {
		return "yoink"
	}
	return out.String()
}

// SortedFilenames returns deterministic file ordering for output writers.
func SortedFilenames(files map[string]string) []string {
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
