package llm

import (
	"fmt"
	"strings"
)

// AssertComposeLayout enforces Yoink's compose-layout invariant: every service
// that has a `build:` block must use `context: ..` and a `dockerfile:` path
// that lives inside the yoink-outputs directory. Returns nil when the compose
// satisfies the invariant, an error describing the first violation otherwise.
//
// The compose file is generated by Yoink at <repo>/yoink-outputs/docker-
// compose.yml. The context "../" reaches back to the repo root so that all
// Dockerfile COPYs are relative to the repository (which is what monorepo
// detection assumes). LLM rewrites that flip the context to "." silently
// break every COPY in the build, with the worst possible error message
// ("requirements.txt: not found"), so guard against it explicitly.
//
// This is a line-based parser rather than a YAML round-trip on purpose: the
// generator emits canonical YAML and we want to reject the change before it
// touches disk, even if the LLM emitted something unusual that still parses
// as YAML (e.g. an inline flow-mapping).
func AssertComposeLayout(compose string) error {
	if strings.TrimSpace(compose) == "" {
		return fmt.Errorf("empty compose")
	}

	inServices := false
	inBuild := false
	currentService := ""
	hasContext := false
	hasDockerfile := false
	contextValid := false
	dockerfileValid := false

	flushService := func() error {
		if !inBuild {
			return nil
		}
		if hasContext && !contextValid {
			return fmt.Errorf("service %q: build.context must be %q (the repo root)", currentService, "..")
		}
		if hasDockerfile && !dockerfileValid {
			return fmt.Errorf("service %q: build.dockerfile must live under yoink-outputs/", currentService)
		}
		inBuild = false
		hasContext = false
		hasDockerfile = false
		contextValid = false
		dockerfileValid = false
		return nil
	}

	for _, line := range strings.Split(compose, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// Top-level key (zero indent, ends with ":").
		if !strings.HasPrefix(line, " ") {
			if err := flushService(); err != nil {
				return err
			}
			currentService = ""
			inServices = strings.HasPrefix(trimmed, "services:")
			continue
		}
		if !inServices {
			continue
		}
		// Service header: exactly 2-space indent + "name:".
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "   ") && strings.HasSuffix(trimmed, ":") {
			if err := flushService(); err != nil {
				return err
			}
			currentService = strings.TrimSuffix(trimmed, ":")
			continue
		}
		// build: header (4-space indent).
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "     ") && trimmed == "build:" {
			inBuild = true
			continue
		}
		// We only care about keys directly under build: (6-space indent).
		if !inBuild || !strings.HasPrefix(line, "      ") || strings.HasPrefix(line, "       ") {
			continue
		}
		key, value, ok := strings.Cut(trimmed, ":")
		if !ok {
			continue
		}
		value = strings.Trim(strings.TrimSpace(value), `"'`)
		switch key {
		case "context":
			hasContext = true
			contextValid = value == ".."
		case "dockerfile":
			hasDockerfile = true
			// Accept any path that lives under the yoink-outputs/ directory.
			dockerfileValid = strings.HasPrefix(value, "yoink-outputs/")
		}
	}
	return flushService()
}
